buildpacks/samples

- nodejs-buildpack/bin/build
Also make sure that if LD_LIBRARY_PATH is empty we do not include the empty path
> Set LD_LIBRARY_PATH from LD_LIBRARY_PATH (not PATH)

- nodejs-buildpack/bin/build
- nodejs-buildpack/bin/detect
- Detects correct Node.js version from package.json using semver.io
- Adds support for vendored apps
- Needs more testing
> Add support for Node.js detection + vendoring

- java-buildpack/bin/build
I also fixed a bug in the default Maven install (when there's no `mvnw`).
> Use wget instead of curl in the java sample

- hello-world-buildpack/README.md
- hello-world-buildpack/bin/build
- hello-world-buildpack/bin/detect
- hello-world-buildpack/buildpack.toml
A minimal no-op buildpack example
> Added a hello world buildpack

- .editorconfig
- Makefile
- buildpacks/hello-moon/README.md
- buildpacks/hello-moon/bin/build
- buildpacks/hello-moon/bin/detect
- buildpacks/hello-moon/buildpack.toml
- buildpacks/hello-world/README.md
- buildpacks/hello-world/bin/build
- buildpacks/hello-world/bin/detect
- buildpacks/java-maven/bin/build
- buildpacks/java-maven/bin/detect
- buildpacks/kotlin-gradle/bin/build
- buildpacks/kotlin-gradle/bin/detect
- buildpacks/ruby-bundler/bin/build
- buildpacks/ruby-bundler/bin/detect
The purpose of these changes are to improve readability of the `detect` and `build` scripts. The contents of this scripts will then be updated on the [tutorial](https://buildpacks.io/docs/create-buildpack/make-buildpack-configurable/).
Signed-off-by: Javier Romero <jromero@pivotal.io>
> Annotate detect and build scripts

- Makefile
- buildpacks/hello-moon/bin/build
- buildpacks/hello-processes/README.md
- buildpacks/hello-processes/bin/build
- buildpacks/hello-processes/bin/detect
- buildpacks/hello-processes/buildpack.toml
- buildpacks/hello-world/bin/build
- buildpacks/hello-world/buildpack.toml
- buildpacks/java-maven/bin/build
- buildpacks/kotlin-gradle/bin/build
- buildpacks/ruby-bundler/bin/build
* Make hello-x IDs consistent
Signed-off-by: Javier Romero <jromero@pivotal.io>
> Add sample of processes

- Makefile
- README.md
Additionally:
- Add support for downloading macOS version of pack
> Update references to buildpacks github org

- .github/workflows/build-and-deploy.yml
Signed-off-by: Andrew Meyer <meyeran@vmware.com>
Signed-off-by: Natalie Arellano <narellano@vmware.com>
> Fix condition in workflow that was causing deploys to skip

- stacks/nanoserver-1809/base/Dockerfile
Signed-off-by: Simon Jones <simonjones@vmware.com>
Signed-off-by: Javier Romero <rjavier@vmware.com>
> Attempt to fix hanging windows tests by using previous tag

- Makefile
- builders/alpine/builder.toml
- builders/bionic/builder.toml
Signed-off-by: Simon Jones <simonjones@vmware.com>
> Package creation and builder package consumption changed with pack 0.9.0

- README.md
Signed-off-by: Simon Jones <simonjones@vmware.com>
> Slack channel and maintainers discoverability

- README.md
- builders/README.md
Signed-off-by: Zander Mackie <zmackie@gmail.com>
> fix samples links

- Makefile
- README.md
This is a trivial change to the README intended to update the sample builders until #75 can be programmatically addressed.
Signed-off-by: Natalie Arellano <narellano@vmware.com>
> Add homepage to README

- .github/workflows/build-and-deploy.yml
* Resolves #75
* Relates to buildpacks/pack#732
Signed-off-by: David Freilich <dfreilich@vmware.com>
> Create and release sample builder upon pack release

- buildpacks/hello-world/bin/build
Adds recursive file listing to platform dir as well as minor reorg.
> Improve hello-world output for platform dir files

- builders/alpine/builder.toml
- builders/bionic/builder.toml
- packages/hello-universe/package.toml
-Fixes samples with pack 0.5.0
Fixes https://github.com/buildpacks/samples/issues/95
> Change builder and package usages of image to docker uris

- Makefile
- builders/nanoserver-1809/builder.toml
- buildpacks/hello-moon-windows/README.md
- buildpacks/hello-moon-windows/bin/build.bat
- buildpacks/hello-moon-windows/bin/detect.bat
- buildpacks/hello-moon-windows/buildpack.toml
- buildpacks/hello-moon/README.md
- buildpacks/hello-universe-windows/README.md
- buildpacks/hello-universe-windows/buildpack.toml
- buildpacks/hello-world-windows/buildpack.toml
- packages/hello-universe-windows/README.md
- packages/hello-universe-windows/package.toml
- packages/hello-world-windows/package.toml
Clones of Linux buildpacks/buildpackages:
* hello-universe
* hello-moon
Signed-off-by: Micah Young <ymicah@vmware.com>
> Adds sample buildpackages for Windows

- apps/batch-script/batch-script-buildpack/bin/build.bat
- buildpacks/dotnet-framework/bin/build.bat
- buildpacks/dotnet-framework/bin/detect.bat
- buildpacks/hello-world-windows/bin/build.bat
- buildpacks/hello-world-windows/bin/detect.bat
- Cleans up Windows concatenate syntax
Signed-off-by: Micah Young <ymicah@vmware.com>
> Updates hello-world-windows with Linux

- Makefile
Signed-off-by: Micah Young <ymicah@vmware.com>
> Fixes deploy: wine stack has no base image

- .github/workflows/build-and-deploy.yml
- Makefile
- builders/dotnet-framework-2004/README.md
- builders/dotnet-framework-2004/builder.toml
- buildpacks/dotnet-framework/buildpack.toml
- buildpacks/hello-moon-windows/buildpack.toml
- buildpacks/hello-world-windows/buildpack.toml
- stacks/dotnet-framework-2004/build/Dockerfile
- stacks/dotnet-framework-2004/run/Dockerfile
Resolves https://github.com/buildpacks/pack/issues/1392
> Add Windows dotnet-framework-2004 resources

- .github/workflows/build-and-deploy.yml
- Makefile
- builders/dotnet-framework-2022/README.md
- builders/dotnet-framework-2022/builder.toml
- buildpacks/dotnet-framework/buildpack.toml
- buildpacks/hello-moon-windows/buildpack.toml
- buildpacks/hello-world-windows/buildpack.toml
- stacks/dotnet-framework-2022/build/Dockerfile
- stacks/dotnet-framework-2022/run/Dockerfile
_Note: failing jobs are unrelated. Need to investigate issues seperately._
> Add Windows 2022 builder

- apps/kotlin-gradle/build.gradle.kts
- apps/kotlin-gradle/gradle/wrapper/gradle-wrapper.properties
**New Dependencies**
- Spring Boot: 2.7.3
- Spring DI: 1.0.13.RELEASE
- Kotlin: 1.7.10
- Gradle: 7.5
> Upgrade Spring Boot 2.7.3 Kotlin 1.7.10 and Gradle 7.5

- .circleci/config.yml
Use the latest Ubuntu image that is available to us
> Update CircelCI executor image

- .github/workflows/build-and-deploy.yml
I think this should (eventually) magically fix both the samples and the docs pipelines
> Bump pack version

- base-images/alpine/run/curl.Dockerfile
Don't know how those lines got in there!
> Fix curl.Dockerfile

- .circleci/config.yml
> Bump pack version for CircleCI

- apps/bash-script/bash-script-buildpack/buildpack.toml
- apps/batch-script/batch-script-buildpack/buildpack.toml
- base-images/build.sh
- buildpacks/dotnet-framework/buildpack.toml
- buildpacks/hello-extensions/buildpack.toml
- buildpacks/hello-moon-windows/buildpack.toml
- buildpacks/hello-moon/buildpack.toml
- buildpacks/hello-processes/buildpack.toml
- buildpacks/hello-universe-windows/buildpack.toml
- buildpacks/hello-universe/buildpack.toml
- buildpacks/hello-world-windows/buildpack.toml
- buildpacks/hello-world/buildpack.toml
- buildpacks/java-maven/buildpack.toml
- buildpacks/kotlin-gradle/buildpack.toml
- buildpacks/ruby-bundler/buildpack.toml
- extensions/curl/extension.toml
- extensions/vim/extension.toml
Use the latest version of the buildpacks API
> Bump samples to buildpacks API 0.10

- builders/alpine/builder.toml
- builders/noble/builder.toml
- buildpacks/hello-extensions/buildpack.toml
- buildpacks/hello-moon/buildpack.toml
- buildpacks/hello-processes/buildpack.toml
- buildpacks/hello-universe/buildpack.toml
- buildpacks/hello-world/buildpack.toml
- buildpacks/java-maven/buildpack.toml
- buildpacks/kotlin-gradle/buildpack.toml
- buildpacks/ruby-bundler/buildpack.toml
Use the base Ubuntu Noble images as our build and run images for mulitarch examples
> Create mulitarch noble builder
