java-buildpack/README.md
java-buildpack/bin/build
java-buildpack/bin/detect
java-buildpack/buildpack.toml

A very basic Java buildpack that runs Maven to compile an app.

 Sample Java buildpack 

---

java-buildpack/bin/build

The jdk buildpack was only creating the jdk layer directory if it would
be different to the previous build's layer. However, it was always
sourcing a profile script from that same directory.
In fixing this, we have completed the 'TODO' items around using the
cache for the jdk.
[buildpack/lifecycle#12]
Signed-off-by: Jacques Chester <jchester@pivotal.io>

Fix rebuilding apps using JDK buildpack

---

gradle-buildpack/README.md
gradle-buildpack/bin/build
gradle-buildpack/bin/detect
gradle-buildpack/buildpack.toml

this supersedes #19 and adds a few improvements. Notably, I've removed support for apps w/o a Gradle wrapper in order to simplify the sample.

Add a Gradle buildpack

---

builder.toml

* removes reference to deleted nodejs buildpack
* adds stack info
Signed-off-by: Emily Casey <ecasey@pivotal.io>
Signed-off-by: Danny Joyce <djoyce@pivotal.io>

fixes builder.toml

---

Makefile
apps/bash-script/bash-script-buildpack/buildpack.toml
builders/alpine/builder.toml
builders/bionic/builder.toml
buildpacks/hello-moon/buildpack.toml
buildpacks/hello-processes/buildpack.toml
buildpacks/hello-universe/buildpack.toml
buildpacks/hello-world/buildpack.toml
buildpacks/java-maven/buildpack.toml
buildpacks/kotlin-gradle/buildpack.toml
buildpacks/ruby-bundler/buildpack.toml

Signed-off-by: Javier Romero <rjavier@vmware.com>

Make buildpack IDs compatible with the registry convention

---

apps/bash-script/bash-script-buildpack/buildpack.toml
buildpacks/hello-moon/buildpack.toml
buildpacks/hello-processes/buildpack.toml
buildpacks/hello-world/buildpack.toml
buildpacks/java-maven/buildpack.toml
buildpacks/kotlin-gradle/buildpack.toml
buildpacks/ruby-bundler/buildpack.toml

It would be very convenient if the sample buildpacks could be used on `io.buildpacks.stacks.bionic`.
Given that the project has defined the `io.buildpacks.stacks.bionic` ID and mixin rules it seems reasonable to me the sample buildpacks should support it, even if we purposefully use a different stack in the builder image (for demonstration purposes).

Buildpacks support io.buildpacks.stacks.bionic

---

buildpacks/java-maven/buildpack.toml
buildpacks/kotlin-gradle/buildpack.toml
buildpacks/ruby-bundler/buildpack.toml

This mixin provides jq and yq shell utilities as defined in https://github.com/buildpacks/rfcs/blob/main/text/0031-bionic-mixins.md\#proposal
Resolves #79

Add build:set=shell-utils mixin to bionic stack where required

---

packages/hello-universe/package.toml

* This demonstrates that packages can also consume images
Signed-off-by: David Freilich <dfreilich@vmware.com>
As part of https://github.com/buildpacks/pack/pull/773, I was trying to demonstrate packaging with pulling images, and I realized that none of our samples repo have. This PR rectifies that.

Update hello-universe to use a public image

---

Makefile
builders/alpine/README.md
builders/bionic/README.md
packages/hello-universe/README.md

* Replace `--builder-config` / `--package-config` with `--config` flag.
* Also replaces `--no-pull` with `--pull-policy=never` flag.
NOTE: This is necessary based on the latest removal of deprecated flags in [pack 0.13.0](https://github.com/buildpacks/pack/releases/tag/v0.13.0).

Replace builder-config/package-config with config flag

---

Makefile

Target was missing from initial PRs
Signed-off-by: Micah Young <ymicah@vmware.com>

Fixes missing make target for windows packages

---

.github/workflows/build-and-deploy.yml
Makefile
builders/README.md
builders/alpine/README.md
builders/bionic/README.md
builders/dotnet-framework-1809/README.md
builders/nanoserver-1809/README.md
packages/hello-universe-windows/README.md
packages/hello-universe/README.md

[Pack v0.16.0](https://github.com/buildpacks/pack/releases/tag/v0.16.0) deprecated a number of commands, including `create-builder` and `package-buildpack`. This change replaces references to the deprecated commands with their new equivalent, using the resource based subcommand model.
Additionally, this change utilizes the new pack config experimental command to set experimental, rather than echoing it into the file.
In the process, this also resolves #100, by replacing references to `create-package` (an old version of the `package-buildpack` command), with the new `pack buildpack package` command.

Update commands to match pack 0.16.0

---

.gitpod.Dockerfile
.gitpod.yml
README.md

Hi buildpacks team,
here is a PR that fully-automates the dev setup of your sample repo with Gitpod, providing anyone with a pre-built, browser-based development environment in one click:
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/*buildpacks/samples)
* Pre-installs the buildpacks CLI tool via apt-get
* Runs `make build-linux` ahead-of-time so you don't need to wait
* Gives anyone immediate access to the pre-compiled buildpacks/samples project, and allows to easily edit & rebuild the code
I hope this can make life easier for contributors, and for maintainers who need to review many PRs (hint: you can already open this PR in Gitpod to easily review & test it without messing up your local checkout).
And I'm looking forward to your …

Gitpodified the repository

---

.github/workflows/build-and-deploy.yml
Makefile
apps/batch-script/batch-script-buildpack/bin/build.bat
apps/batch-script/batch-script-buildpack/buildpack.toml
builders/wine/README.md
builders/wine/builder.toml
buildpacks/hello-moon-windows/buildpack.toml
buildpacks/hello-world-windows/buildpack.toml
stacks/wine/build/Dockerfile
stacks/wine/build/bin/lifecycle-wrapper.sh
stacks/wine/run/Dockerfile

This adds stacks and builders to let users, buildpack authors and lifecycle contributors have access to a Windows-like  environments during build/detect phases, using only a Linux daemon. It can also help more advanced contributors to understand the differences between Linux and Windows functionality. It may also help catch and debug Windows bugs in cnb components.
The main limitations are:
* Wine's emulation is very similar to native WCOW but not identical.
* Generated app images are Windows-formatted and realistically runnable on Linux daemon, so run image is based on `scratch` to limit confusion.
* Buildpackages cannot be used as they'd confusingly need to be Linux-formatted but would be added intact to the generated Windows-formatted image.
More background and usage described in …

Adds wine stack & builder to demonstrate Windows without a WCOW daemon

---

.circleci/config.yml
.github/workflows/build-and-deploy.yml
stacks/README.md
stacks/build-stack.sh
stacks/wine/build/Dockerfile

* Wrong pack binary selected
* Now that pack produces linux-arm64, the CI pipeline is picking up the wrong variant. This fix adds additional string matching to select the proper variant.
* pack orb pinned to old dev version
* Since [dev versions are only kept for 90 days](https://discuss.circleci.com/t/orb-dev-release/42792), ours had expired.
* Orb version pinned to a _minor_ version of `0.2` to prevent having to update the version for patch releases.
* wine stack not building
* We were using an EOL version of ubuntu (groovy) as the base image
* Additionally, we set a default platform of amd64 to be able to install i386 dependencies on arm64-based systems.

CI: Fix: Various CI issues

---

.github/workflows/build-and-deploy.yml
Makefile

We were missing a make target of deploy-windows-2022.
Additionally, this commit separates building and deploying Windows packages
to its own job.

CI: Fix: Windows build and deploy pipeline

---

stacks/bionic/base/Dockerfile

The ruby distribution now ships with bundle by default.  However, it requires that libyaml is available.  We supply libyaml in our base sample image in order to simplify our documentation.
Signed-off-by: Aidan Delaney <adelaney21@bloomberg.net>

Add libyaml to allow ruby version bump

---

Makefile

In the image published to Docker Hub, /cnb/extensions is empty

Test that extensions are present in alpine builder

---

buildpacks/hello-moon/buildpack.toml
buildpacks/hello-processes/buildpack.toml
buildpacks/hello-world/buildpack.toml
buildpacks/java-maven/buildpack.toml
buildpacks/kotlin-gradle/buildpack.toml
buildpacks/ruby-bundler/buildpack.toml

Expand the stacks that we support for sample buildpacks
Fixes #139

Allow sample buildpacks on all stacks

---

.github/workflows/build-and-deploy.yml

Use the syntax from the Github Actions documentation
https://docs.github.com/en/actions/learn-github-actions/expressions

Simplify condition to deploy on main

---

.circleci/config.yml

The default pack version on CircleCI is 0.18.  Use the
latest version.

Update pack version for CircleCI

---

apps/bash-script/bash-script-buildpack/bin/build
apps/batch-script/batch-script-buildpack/bin/build.bat

In the example we are using Buildpacks API 0.9
https://github.com/buildpacks/samples/blob/main/apps/bash-script/bash-script-buildpack/buildpack.toml#L2 which requires to have a `command = [something]` as specified in the spec: https://github.com/buildpacks/spec/blob/buildpack/v0.9/buildpack.md#launchtoml-toml
But in the builder we have a string instead of an array, causing an error when processed: https://github.com/buildpacks/samples/blob/main/apps/bash-script/bash-script-buildpack/bin/build#L13 
This PR just fix that putting the `./app.bat` or `./app.sh` command into an array

Fix the command parameter to work with Buildpacks API 0.9

---

Makefile

So that it can be deployed later
This should fix the Windows pipeline that was broken with https://github.com/buildpacks/samples/pull/172, where we try to deploy a stack that wasn't built yet

Build nanoserver along with dotnet framework

---

Makefile
buildpacks/hello-universe-windows/package.toml
buildpacks/hello-universe/package.toml
buildpacks/hello-world-windows/package.toml
buildpacks/hello-world/package.toml
packages/README.md
packages/hello-universe-windows/README.md
packages/hello-universe/README.md
packages/hello-world-windows/package.toml
packages/hello-world/package.toml

Having everything in one directory is more convenient and more discoverable

Move package.toml to be under buildpacks/

---

Makefile
base-images/jammy/base/Dockerfile
buildpacks/java-maven/bin/build
buildpacks/kotlin-gradle/bin/build

The exec.d scripts in maven and kotlin examples were not outputting key="value" pairs to stdout.

Correct redirects in JVM exec.d scripts

---

buildpacks/java-maven/bin/build
buildpacks/kotlin-gradle/bin/build

Set JAVA_HOME and LD_LIBRARY_PATH using evn.default and env.append. This removes some logic from the build script.

Replace exec.d script with env dir

---

buildpacks/java-maven/bin/build

Older versions of maven are no longer available at the download URL.

Bump maven version
